const KEY='bread-bucks-v1';let mode='login',page='dashboard',state=null;
const seedCompanies=[
{id:'c1',name:'ToastTech',industry:'Technology',description:'Smart tools for everyday businesses.',owner:'BreadBot',pop:82,revenue:5400,profit:1900,value:76000,growth:8.4,shares:1000,available:300,sharePrice:76,next:Date.now()+540000},
{id:'c2',name:'Golden Crust',industry:'Food',description:'A premium bakery brand going viral.',owner:'BreadBot',pop:67,revenue:3800,profit:1450,value:52000,growth:6.2,shares:1000,available:450,sharePrice:52,next:Date.now()+720000},
{id:'c3',name:'Pixel Fuel',industry:'Gaming',description:'Fast, fun games for everyone.',owner:'BreadBot',pop:74,revenue:4700,profit:1600,value:61000,growth:7.1,shares:1000,available:220,sharePrice:61,next:Date.now()+310000}
];
function blank(){return{users:{},companies:structuredClone(seedCompanies),marketEvents:[],session:null}}
function load(){state=JSON.parse(localStorage.getItem(KEY)||'null')||blank();if(!state.companies)state.companies=structuredClone(seedCompanies)}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function user(){return state.users[state.session]}
function money(n){return Math.round(n).toLocaleString()}
function toast(t){const e=document.getElementById('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function auth(){document.getElementById('auth').classList.toggle('hidden',!!state.session);document.getElementById('app').classList.toggle('hidden',!state.session);if(state.session)render()}
function authForm(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{mode=b.dataset.auth;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));document.getElementById('authSubmit').textContent=mode==='login'?'Log in':'Create account';document.getElementById('authMsg').textContent=''})
document.getElementById('authForm').onsubmit=e=>{e.preventDefault();const u=document.getElementById('authUser').value.trim().toLowerCase(),p=document.getElementById('authPass').value;if(mode==='signup'){if(state.users[u])return msg('Username already exists.');state.users[u]={username:u,password:p,bb:10000,companies:[],investments:{},transactions:[],created:Date.now()};state.session=u;save();auth();toast('Account created — +10,000 BB')}else{if(!state.users[u]||state.users[u].password!==p)return msg('Incorrect username or password.');state.session=u;save();auth();toast('Welcome back!')}};document.getElementById('demoBtn').onclick=()=>{if(!state.users.demoplayer)state.users.demoplayer={username:'demoplayer',password:'demo',bb:10000,companies:[],investments:{},transactions:[],created:Date.now()};state.session='demoplayer';save();auth()};document.getElementById('logout').onclick=()=>{state.session=null;save();auth()}}
function msg(t){document.getElementById('authMsg').textContent=t}
function nav(){document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{page=b.dataset.page;document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x===b));render()})}
function render(){document.getElementById('balance').textContent=money(user().bb);document.getElementById('username').textContent='@'+user().username;const main=document.getElementById('main');const views={dashboard:dashboard,companies:companies,market:market,investments:investments,leaderboard:leaderboard,transactions:transactions};main.innerHTML=views[page]();bindView();}
function dashboard(){const u=user(), mine=state.companies.filter(c=>c.owner===u.username);const invVal=Object.values(u.investments).reduce((s,x)=>s+x.shares*x.price,0);return `<div class="page-head"><div><h1>Good business starts with bread.</h1><p>Your virtual economy at a glance.</p></div><button class="primary" onclick="openCompany()">+ Create company</button></div><div class="grid"><div class="card stat"><div class="label">BB BALANCE</div><div class="value">${money(u.bb)} <small>BB</small></div></div><div class="card stat"><div class="label">COMPANY VALUE</div><div class="value">${money(mine.reduce((s,c)=>s+c.value,0))} <small>BB</small></div></div><div class="card stat"><div class="label">INVESTMENTS</div><div class="value">${money(invVal)} <small>BB</small></div></div><div class="card stat"><div class="label">COMPANIES</div><div class="value">${mine.length}</div></div></div><div class="section"><div class="section-title"><h2>My companies</h2><button class="ghost" onclick="page='companies';render()">View all</button></div>${mine.length?`<div class="company-grid">${mine.slice(0,3).map(companyCard).join('')}</div>`:`<div class="empty">You don't own a company yet.<br><button class="primary" style="margin-top:12px" onclick="openCompany()">Build your first company</button></div>`}</div><div class="section"><div class="section-title"><h2>Market movers</h2></div><div class="company-grid">${[...state.companies].sort((a,b)=>b.growth-a.growth).slice(0,3).map(companyCard).join('')}</div></div>`}
function companyCard(c){return `<div class="card company-card"><div class="industry">${c.industry.toUpperCase()}</div><h3>${c.name}</h3><div class="desc">${c.description}</div><div class="metrics"><div class="metric"><small>POPULARITY</small><b>${c.pop}%</b><div class="bar"><i style="width:${c.pop}%"></i></div></div><div class="metric"><small>VALUE</small><b>${money(c.value)} BB</b></div><div class="metric"><small>SHARE PRICE</small><b>${money(c.sharePrice)} BB</b></div><div class="metric"><small>GROWTH</small><b class="positive">+${c.growth.toFixed(1)}%</b></div></div><div class="actions"><button class="ghost" onclick="openDetails('${c.id}')">Details</button>${c.owner!==user().username?`<button class="primary" onclick="openInvest('${c.id}')">Invest</button>`:''}</div></div>`}
function companies(){const mine=state.companies.filter(c=>c.owner===user().username);return `<div class="page-head"><div><h1>My Companies</h1><p>Build as many businesses as you want — creation costs 0 BB.</p></div><button class="primary" onclick="openCompany()">+ Create company</button></div>${mine.length?`<div class="company-grid">${mine.map(companyCard).join('')}</div>`:`<div class="empty">No companies yet. Create one for free.</div>`}`}
function market(){return `<div class="page-head"><div><h1>Marketplace</h1><p>Find companies and invest BB into available shares.</p></div></div><div class="searchrow"><input id="marketSearch" placeholder="Search companies..."><select id="sort"><option value="pop">Most popular</option><option value="growth">Highest growth</option><option value="value">Highest value</option><option value="price">Lowest share price</option></select></div><div id="marketList" class="company-grid"></div>`}
function renderMarket(){let arr=state.companies.filter(c=>c.owner!==user().username);const q=(document.getElementById('marketSearch')?.value||'').toLowerCase();arr=arr.filter(c=>(c.name+c.industry+c.owner).toLowerCase().includes(q));const s=document.getElementById('sort')?.value||'pop';arr.sort((a,b)=>s==='growth'?b.growth-a.growth:s==='value'?b.value-a.value:s==='price'?a.sharePrice-b.sharePrice:b.pop-a.pop);document.getElementById('marketList').innerHTML=arr.length?arr.map(companyCard).join(''):'<div class="empty">No matching companies.</div>'}
function investments(){const inv=Object.values(user().investments);const total=inv.reduce((s,x)=>s+x.shares*x.price,0);return `<div class="page-head"><div><h1>Investments</h1><p>Your share portfolio and unrealised profit.</p></div></div><div class="grid"><div class="card stat"><div class="label">PORTFOLIO VALUE</div><div class="value">${money(total)} BB</div></div><div class="card stat"><div class="label">POSITIONS</div><div class="value">${inv.length}</div></div></div><div class="section card">${inv.length?`<table class="table"><thead><tr><th>COMPANY</th><th>SHARES</th><th>AVG PRICE</th><th>NOW</th><th>P/L</th><th></th></tr></thead><tbody>${inv.map(x=>{const c=state.companies.find(c=>c.id===x.companyId);const pl=(c.sharePrice-x.avg)*x.shares;return `<tr><td>${c?.name||'Unknown'}</td><td>${x.shares}</td><td>${money(x.avg)} BB</td><td>${money(c?.sharePrice||x.price)} BB</td><td class="${pl>=0?'positive':'negative'}">${pl>=0?'+':''}${money(pl)} BB</td><td><button class="ghost" onclick="sell('${x.companyId}')">Sell</button></td></tr>`}).join('')}</tbody></table>`:'<div class="empty">You haven't invested yet. Visit the marketplace.</div>'}</div>`}
function leaderboard(){const players=Object.values(state.users).sort((a,b)=>b.bb-a.bb);const companies=[...state.companies].sort((a,b)=>b.value-a.value);return `<div class="page-head"><div><h1>Leaderboard</h1><p>See who is dominating the virtual economy.</p></div></div><div class="grid"><div class="card"><h3>💰 Richest players</h3>${players.slice(0,8).map((p,i)=>`<p><b>#${i+1}</b> @${p.username} <span style="float:right">${money(p.bb)} BB</span></p>`).join('')}</div><div class="card"><h3>🏢 Most valuable</h3>${companies.slice(0,8).map((c,i)=>`<p><b>#${i+1}</b> ${c.name} <span style="float:right">${money(c.value)} BB</span></p>`).join('')}</div></div>`}
function transactions(){return `<div class="page-head"><div><h1>Transactions</h1><p>Your BB activity.</p></div></div><div class="card"><table class="table"><thead><tr><th>TIME</th><th>TYPE</th><th>DETAIL</th><th>AMOUNT</th></tr></thead><tbody>${(user().transactions||[]).slice().reverse().map(t=>`<tr><td>${new Date(t.time).toLocaleString()}</td><td>${t.type}</td><td>${t.detail}</td><td class="${t.amount>=0?'positive':'negative'}">${t.amount>=0?'+':''}${money(t.amount)} BB</td></tr>`).join('')||'<tr><td colspan="4">No transactions yet.</td></tr>'}</tbody></table></div>`}
function openCompany(){modal(`<h2>Create a company</h2><p class="muted">It costs 0 BB to launch. You can build unlimited companies.</p><form id="companyForm"><div class="formgrid"><input id="cn" placeholder="Company name" required><select id="ci"><option>Technology</option><option>Food</option><option>Gaming</option><option>Sports</option><option>Transport</option><option>Fashion</option><option>Entertainment</option><option>Finance</option><option>Energy</option><option>Other</option></select><textarea id="cd" class="wide" placeholder="What does your company do?" required></textarea></div><button class="primary full">Launch company</button></form>`);document.getElementById('companyForm').onsubmit=e=>{e.preventDefault();const c={id:'c'+crypto.randomUUID(),name:document.getElementById('cn').value.trim(),industry:document.getElementById('ci').value,description:document.getElementById('cd').value.trim(),owner:user().username,pop:20,revenue:800,profit:300,value:10000,growth:2.5,shares:1000,available:800,sharePrice:10,next:Date.now()+900000};state.companies.push(c);user().companies.push(c.id);user().transactions.push({time:Date.now(),type:'Company',detail:`Launched ${c.name}`,amount:0});save();closeModal();render();toast(`${c.name} launched!`)} }
function openInvest(id){const c=state.companies.find(x=>x.id===id);modal(`<h2>Invest in ${c.name}</h2><p class="muted">${c.pop}% popularity · ${money(c.sharePrice)} BB/share · ${c.available} shares available</p><form id="investForm"><input id="shares" type="number" min="1" max="${c.available}" value="1" required><button class="primary full">Buy shares</button></form>`);document.getElementById('investForm').onsubmit=e=>{e.preventDefault();const n=Math.floor(+document.getElementById('shares').value),cost=n*c.sharePrice;if(n<1||n>c.available)return; if(user().bb<cost)return toast('Not enough BB');user().bb-=cost;c.available-=n;let inv=user().investments[id];if(!inv)inv={companyId:id,shares:0,avg:0,price:c.sharePrice};inv.avg=(inv.avg*inv.shares+cost)/(inv.shares+n);inv.shares+=n;inv.price=c.sharePrice;user().investments[id]=inv;user().transactions.push({time:Date.now(),type:'Investment',detail:`Bought ${n} shares of ${c.name}`,amount:-cost});save();closeModal();render();toast(`Invested ${money(cost)} BB`)} }
function sell(id){const inv=user().investments[id],c=state.companies.find(x=>x.id===id);if(!inv||!c)return;const amount=inv.shares*c.sharePrice;user().bb+=amount;c.available+=inv.shares;user().transactions.push({time:Date.now(),type:'Sale',detail:`Sold ${inv.shares} shares of ${c.name}`,amount});delete user().investments[id];save();render();toast(`Sold for ${money(amount)} BB`)}
function openDetails(id){const c=state.companies.find(x=>x.id===id);const remaining=Math.max(0,c.next-Date.now());modal(`<h2>${c.name}</h2><p class="muted">${c.industry} · owned by @${c.owner}</p><div class="metrics"><div class="metric"><small>POPULARITY</small><b>${c.pop}%</b></div><div class="metric"><small>PROFIT / CYCLE</small><b>${money(c.profit)} BB</b></div><div class="metric"><small>VALUE</small><b>${money(c.value)} BB</b></div><div class="metric"><small>NEXT PAYOUT</small><b class="countdown" data-time="${c.next}">${fmt(remaining)}</b></div></div><p class="muted">Payouts happen every 15 minutes. When a cycle completes, profits are distributed automatically based on ownership.</p>${c.owner===user().username?`<button class="primary full" onclick="boost('${id}')">Reinvest 500 BB</button>`:''}`)}
function boost(id){const c=state.companies.find(x=>x.id===id);if(user().bb<500)return toast('You need 500 BB');user().bb-=500;c.pop=Math.min(100,c.pop+5);c.growth+=1;c.revenue+=180;c.profit+=70;c.value+=1200;c.sharePrice=c.value/c.shares;user().transactions.push({time:Date.now(),type:'Upgrade',detail:`Marketing boost for ${c.name}` ,amount:-500});save();closeModal();render();toast('Company upgraded!')}
function fmt(ms){let s=Math.max(0,Math.floor(ms/1000)),m=Math.floor(s/60),r=s%60;return `${String(m).padStart(2,'0')}:${String(r).padStart(2,'0')}`}
function modal(body){const old=document.getElementById('modal');if(old)old.remove();const d=document.createElement('div');d.id='modal';d.className='modal';d.innerHTML=`<div class="modal-card"><div class="modal-head"><div></div><button class="close" onclick="closeModal()">×</button></div>${body}</div>`;document.body.appendChild(d)}function closeModal(){document.getElementById('modal')?.remove()}
function bindView(){if(page==='market'){renderMarket();document.getElementById('marketSearch').oninput=renderMarket;document.getElementById('sort').onchange=renderMarket}}
function simulate(){const now=Date.now();state.companies.forEach(c=>{const elapsed=Math.floor((now-c.next)/900000)+1;if(now>=c.next){const cycles=Math.min(4,elapsed);for(let i=0;i<cycles;i++)payout(c);c.next=now+900000}else{c.pop=Math.max(1,Math.min(100,c.pop+(Math.random()-.42)*.15));c.value=Math.max(1000,c.value*(1+c.growth/100/3600));c.sharePrice=c.value/c.shares}});save();if(state.session){render();document.querySelectorAll('[data-time]').forEach(e=>e.textContent=fmt(+e.dataset.time-Date.now()))}}
function payout(c){const profit=Math.max(50,Math.round(c.profit*(.8+Math.random()*.5)));const owners=[];Object.values(state.users).forEach(u=>{const inv=u.investments?.[c.id];if(inv)owners.push([u,inv.shares])});const ownerShares=c.shares-c.available;const totalOwned=Math.max(ownerShares,1);owners.forEach(([u,shares])=>{const amount=Math.round(profit*shares/totalOwned);u.bb+=amount;u.transactions.push({time:Date.now(),type:'Payout',detail:`${c.name} investor payout`,amount})});const owner=state.users[c.owner];if(owner){const own=ownerShares-owners.reduce((s,[u,n])=>s+(u.username===owner.username?n:0),0);const amount=Math.max(0,profit-owners.reduce((s,[u,n])=>s+Math.round(profit*n/totalOwned),0));owner.bb+=amount;owner.transactions.push({time:Date.now(),type:'Payout',detail:`${c.name} owner payout`,amount})}c.pop=Math.min(100,c.pop+Math.random()*2);c.profit=Math.max(50,Math.round(c.profit*(1+(.03+Math.random()*.08))));c.value*=1.01;c.sharePrice=c.value/c.shares}
load();authForm();nav();auth();setInterval(simulate,1000);window.openCompany=openCompany;window.openInvest=openInvest;window.sell=sell;window.openDetails=openDetails;window.boost=boost;window.closeModal=closeModal;
